### ISSUE TITLE
I think there is a typo, either in the article or in the code

### ISSUE THREAD

**Issue by delkind-dnsf** [acmi-lab/PU_learning#3]
https://github.com/acmi-lab/PU_learning/blob/a9174bda92c7411906056c789011cfa41749ee5f/estimator.py#L66

Line 66 appears to be the UCB portion from Algorithm 1 in the arXiv paper ("method 2"). But the paper "Mixture Proportion Estimation and PU Learning: A Modern Approach" says sqrt(log(4 / delta) / 2 / n), whereas the code says sqrt(log(1 / delta) / 2 / n). 

So I think there is a typo somewhere, either in the code or in the paper.

**Comment by saurabhgarg1996** [comment]
Updated, thank you for catching that.
